import fs from 'fs/promises'
import type { ReportData, Ticket, SprintPlan } from '../types.js'

export async function renderMarkdownReport(
  data: ReportData,
  outputPath: string
): Promise<void> {
  const md = buildMarkdown(data)
  await fs.writeFile(outputPath, md, 'utf-8')
}

function buildMarkdown(data: ReportData): string {
  const { decomposition, sprintPlans, dependencyGraph, config } = data
  const byId = new Map(decomposition.tickets.map((t) => [t.id, t]))
  const lines: string[] = []

  // Header
  const titleParts = [config.teamName, config.sprintName].filter(Boolean)
  const title = titleParts.length ? titleParts.join(' • ') : 'Sprint Plan'
  lines.push(`# ${title}`)
  lines.push('')
  lines.push(
    `_Generated by [spec-sprint](https://github.com/Srikanth-AD/spec-sprint) v${data.version} on ${new Date(data.generatedAt).toISOString().slice(0, 10)}_`
  )
  lines.push('')
  lines.push(
    `**${decomposition.tickets.length}** tickets · **${decomposition.epics.length}** epics · **${sprintPlans.length}** sprints · **${decomposition.totalPoints}** points · **${config.teamSize}** engineers @ **${config.velocity}** pts/sprint`
  )
  lines.push('')
  lines.push(`**Spec source:** \`${data.specSource}\``)
  lines.push('')

  // Summary
  if (decomposition.specSummary) {
    lines.push('## Summary')
    lines.push('')
    lines.push(decomposition.specSummary)
    lines.push('')
  }

  // Assumptions / Risks
  if (decomposition.assumptions.length || decomposition.risks.length) {
    if (decomposition.assumptions.length) {
      lines.push('## Assumptions')
      lines.push('')
      decomposition.assumptions.forEach((a) => lines.push(`- ${a}`))
      lines.push('')
    }
    if (decomposition.risks.length) {
      lines.push('## Risks')
      lines.push('')
      decomposition.risks.forEach((r) => lines.push(`- ${r}`))
      lines.push('')
    }
  }

  // Sprint overview
  lines.push('## Sprint overview')
  lines.push('')
  lines.push('| Sprint | Tickets | Points | Capacity | Utilization | Warnings |')
  lines.push('|---|---|---|---|---|---|')
  sprintPlans.forEach((p) => {
    const util = `${p.totalPoints} / ${p.capacityPoints} (${p.utilizationPct}%)`
    lines.push(
      `| Sprint ${p.sprintNumber} | ${p.ticketIds.length} | ${p.totalPoints} | ${p.capacityPoints} | ${util} | ${p.warnings.length || '—'} |`
    )
  })
  lines.push('')

  // Critical path
  if (dependencyGraph.criticalPath.length) {
    const cpPts = dependencyGraph.criticalPath.reduce(
      (s, id) => s + (byId.get(id)?.storyPoints ?? 0),
      0
    )
    lines.push('## Critical path')
    lines.push('')
    lines.push(
      `${dependencyGraph.criticalPath.join(' → ')} _(${cpPts} pts minimum)_`
    )
    lines.push('')
    lines.push('| ID | Title | Points | Skill |')
    lines.push('|---|---|---|---|')
    dependencyGraph.criticalPath.forEach((id) => {
      const t = byId.get(id)
      if (t) lines.push(`| \`${t.id}\` | ${escape(t.title)} | ${t.storyPoints} | ${t.skillArea} |`)
    })
    lines.push('')
  }

  // Epics
  if (decomposition.epics.length) {
    lines.push('## Epics')
    lines.push('')
    lines.push('| Epic | Title | Tickets | Points | Sprint span |')
    lines.push('|---|---|---|---|---|')
    decomposition.epics.forEach((e) => {
      lines.push(
        `| \`${e.id}\` | ${escape(e.title)} | ${e.ticketIds.length} | ${e.totalPoints} | ${e.sprintSpan} |`
      )
    })
    lines.push('')
  }

  // Per-sprint sections
  sprintPlans.forEach((p) => {
    lines.push(`## Sprint ${p.sprintNumber}`)
    lines.push('')
    lines.push(
      `**${p.totalPoints} / ${p.capacityPoints} pts (${p.utilizationPct}%)**`
    )
    lines.push('')

    const skillEntries = Object.entries(p.skillBreakdown)
    if (skillEntries.length) {
      lines.push(
        'Skill breakdown: ' +
          skillEntries.map(([k, v]) => `**${k}** ${v}pts`).join(' · ')
      )
      lines.push('')
    }

    if (p.warnings.length) {
      lines.push('> ⚠ ' + p.warnings.join('  \n> ⚠ '))
      lines.push('')
    }

    lines.push('| ID | Title | Story | Pts | Skill | Priority | Blocked by |')
    lines.push('|---|---|---|---|---|---|---|')
    p.ticketIds.forEach((id) => {
      const t = byId.get(id)
      if (!t) return
      const story = escape(truncate(t.userStory, 70))
      const blocked = t.blockedBy.length
        ? t.blockedBy.map((b) => `\`${b}\``).join(', ')
        : '—'
      lines.push(
        `| \`${t.id}\` | ${escape(t.title)} | ${story} | ${t.storyPoints} | ${t.skillArea} | ${t.priority} | ${blocked} |`
      )
    })
    lines.push('')

    // Ticket details (collapsible per ticket)
    lines.push(`<details><summary>Sprint ${p.sprintNumber} ticket details</summary>`)
    lines.push('')
    p.ticketIds.forEach((id) => {
      const t = byId.get(id)
      if (!t) return
      lines.push(...renderTicketDetail(t))
    })
    lines.push('')
    lines.push('</details>')
    lines.push('')
  })

  lines.push('---')
  lines.push('')
  lines.push(
    '_Estimates are starting points for team discussion, not commitments._'
  )
  lines.push('')

  return lines.join('\n')
}

function renderTicketDetail(t: Ticket): string[] {
  const out: string[] = []
  out.push('')
  out.push(`#### \`${t.id}\` — ${t.title}`)
  out.push('')
  out.push(
    `**${t.storyPoints} pts** · ${t.skillArea} · ${t.priority}` +
      (t.sprint != null ? ` · Sprint ${t.sprint}` : '')
  )
  out.push('')
  if (t.userStory) {
    out.push(`> ${t.userStory}`)
    out.push('')
  }
  if (t.description) {
    out.push(t.description)
    out.push('')
  }
  if (t.acceptanceCriteria.length) {
    out.push('**Acceptance criteria:**')
    out.push('')
    t.acceptanceCriteria.forEach((ac) => {
      out.push(`- Given ${ac.given}, when ${ac.when}, then ${ac.then}`)
    })
    out.push('')
  }
  if (t.blockedBy.length) {
    out.push(
      '**Blocked by:** ' + t.blockedBy.map((b) => `\`${b}\``).join(', ')
    )
    out.push('')
  }
  if (t.rationale) {
    out.push(`_Estimate rationale: ${t.rationale}_`)
    out.push('')
  }
  return out
}

function escape(s: string): string {
  return String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function truncate(s: string, n: number): string {
  if (!s) return ''
  return s.length > n ? s.slice(0, n) + '…' : s
}
